# Boot preset: UEFI + GRUB
#
# Copied automatically into system/boot.nix by install.sh when an ESP is detected.
# systemd-boot is deliberately DISABLED here: the two must never be active at
# the same time, otherwise the old menu (usually systemd-boot, generated by
# default by nixos-generate-config) stays as the priority entry and GRUB looks
# like it "didn't install".
{ ... }:
{
  boot.loader.systemd-boot.enable = false;

  boot.loader.efi.canTouchEfiVariables = true;
  # Change this path if your ESP isn't mounted at /boot (check with `lsblk`
  # and the fileSystems."/boot" line in hardware-configuration.nix).
  boot.loader.efi.efiSysMountPoint = "/boot";

  boot.loader.grub = {
    enable = true;
    device = "nodev";       # required on UEFI: GRUB installs into the ESP, not onto a disk
    efiSupport = true;
    efiInstallAsRemovable = true; # handy for dual-boot / VMs / finicky Secure Boot setups
    useOSProber = true;     # detects Windows/other OSes for the boot menu
  };
}
